export const FETCH_HOT_MOVIE = "project3/HomePage/FETCH_HOT_MOVIE";
export const FETCH_HOT_MOVIE_SUCCESS = "project3/HomePage/FETCH_HOT_MOVIE_SUCCESS";
export const FETCH_HOT_MOVIE_ERROR = "project3/HomePage/FETCH_HOT_MOVIE_ERROR";
export const FETCH_HOT_CURRENTMOVIE = "project3/HomePage/FETCH_HOT_CURRENTMOVIE";
export const FETCH_HOT_CURRENTMOVIE_SUCCESS = "project3/HomePage/FETCH_HOT_CURRENTMOVIE_SUCCESS";
export const FETCH_HOT_CURRENTMOVIE_ERROR = "project3/HomePage/FETCH_HOT_CURRENTMOVIE_ERROR";
export const FETCH_HOT_UPCOMMINGMOVIE = "project3/HomePage/FETCH_HOT_UPCOMMINGMOVIE";
export const FETCH_HOT_UPCOMMINGMOVIE_SUCCESS = "project3/HomePage/FETCH_HOT_UPCOMMINGMOVIE_SUCCESS";
export const FETCH_HOT_UPCOMMINGMOVIE_ERROR = "project3/HomePage/FETCH_HOT_UPCOMMINGMOVIE_ERROR";

